### ISSUE TITLE
(yarn run deploy) error - command failed with exit code 1 

### ISSUE THREAD

**Issue by Nivaschill** [dwaynelavon/DigitalResumeSkeleton#1]
Hello,
I'm trying to deploy but it is showing an error message saying command failed with exit code 1. can you please help me in fixing this. thank you

**PS C:\Users\nivas\OneDrive\Documents\GitHub\DigitalResumeSkeleton\app> yarn run deploy
yarn run v1.13.0
warning ..\package.json: No license field
$ yarn run build
warning ..\package.json: No license field
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  139.15 KB  build\static\js\main.fca3c7f6.js
  687 B      build\static\css\main.3553a732.css

The project was built assuming it is hosted at /app/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
To publish it at https://nivaschill.github.io/app, run:

  yarn run deploy

$ gh-pages -d build
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**

**Comment by dwaynelavon** [comment]
@Nivaschill I will take a look at this and see if can reproduce
